# This workflow will RUN an un-built go app  
# As an example, when ran against this repo,  
# it logs the output of "Hello World!"  

name: RUN main.go

# on:
#   push:
#     branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]

on:
  schedule:
    # https://crontab.guru/#407_03_26_*_*
    - cron: '07 03 26 * *'



jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          check-latest: true

          
      - name: Install dependencies
        run: go run .
        
      # - name: Test with Go
      #   run: go test -json > TestResults-${{ GITHUB.RUN.ID }}-${{ GITHUB.RUN.ATTEMPT }}.json
        
      # - name: Upload Go test results
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: Go-results-${{ GITHUB.RUN.ID }}-${{ GITHUB.RUN.ATTEMPT }}
      #     path: TestResults-${{ GITHUB.RUN.ID }}-${{ GITHUB.RUN.ATTEMPT }}.json
